# Generated by Django 5.2.1 on 2025-05-07 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SyncEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('device_id', models.CharField(max_length=100)),
                ('timestamp', models.DateTimeField()),
                ('total_files_synced', models.IntegerField()),
                ('total_errors', models.IntegerField()),
                ('internet_speed', models.FloatField()),
            ],
        ),
    ]
